
# Networking
CONFIG_NETWORKING=y
CONFIG_NET_TCP=y
CONFIG_NET_SOCKETS=y
CONFIG_POSIX_API=y
CONFIG_NET_L2_ETHERNET=y

# Enable the entropy driver needed for networking
CONFIG_ENTROPY_GENERATOR=y
CONFIG_TEST_RANDOM_GENERATOR=y

# SPI
CONFIG_SPI=y
CONFIG_SPI_BITBANG=y

# GPIO
CONFIG_GPIO=y

# Ethernet Driver
CONFIG_ETH_W6300=y
